In [161]:
from pathlib import Path
import pandas as pd
import numpy as np
import importlib
import Ekrt.sf_project.load_data.loader as loader
importlib.reload(loader)

from Ekrt.refactor.prediction_models import optimal_setting
from Ekrt.sf_project.load_data.loader import DataConfig, LoadRawData,PricePanelBuilder, BidAskPanelBuilder, PanelSaver

In [149]:
data = optimal_setting.load_project_data() #Load original data

cfg = DataConfig(data_dir=Path("/Users/filipekrt/SF/data")) #path kde jsou úplně původní data
loader = LoadRawData(cfg = cfg)
price_panel = PricePanelBuilder(loader = loader)
bid_ask_panel = BidAskPanelBuilder(loader = loader)

In [129]:
#Load prices and bid ask - OUT OF SAMPLE DATA
months_out = ["october","november","december"]
df_bidask_out = bid_ask_panel.combine_months(months = months_out)
dict_prices_out = price_panel.combine_months(months = months_out)

#Save three files
absolute_path = Path("/Users/filipekrt/SF/Ekrt/sf_project/load_data")
PanelSaver.save_price_panel(dict_prices_out, path = absolute_path / "prices_out_of_sample.parquet")
PanelSaver.save_price_long(dict_prices_out, path = absolute_path / "prices_out_of_sample_w_contract_id.parquet")
PanelSaver.save_bidask_panel(df_bidask_out, path = absolute_path / "bidask_out_of_sample.parquet")

october is DONE
november is DONE
december is DONE
october is DONE
november is DONE
december is DONE
Saved /Users/filipekrt/SF/Ekrt/sf_project/load_data/prices_out_of_sample.parquet

In [138]:
#Load prices and bid ask - IN SAMPLE
months_in = ["march","april","may","june","july","august","september"]
df_bidask_in = bid_ask_panel.combine_months(months = months_in)
dict_prices_in = price_panel.combine_months(months = months_in)

#Saves three files
PanelSaver.save_price_panel(dict_prices_in, path = absolute_path / "prices_in_sample.parquet")
PanelSaver.save_price_long(dict_prices_in, path = absolute_path / "prices_in_sample_w_contract_id.parquet")
PanelSaver.save_bidask_panel(df_bidask_in, path = absolute_path / "bidask_in_sample.parquet")

march is DONE
april is DONE
may is DONE
june is DONE
july is DONE
august is DONE
september is DONE
march is DONE
april is DONE
may is DONE
june is DONE
july is DONE
august is DONE
september is DONE
Saved /Users/filipekrt/SF/Ekrt/sf_project/load_data/prices_in_sample.parquet
Saved /Users/filipekrt/SF/Ekrt/sf_project/load_data/prices_in_sample_w_contract_id.parquet
Saved /Users/filipekrt/SF/Ekrt/sf_project/load_data/bidask_in_sample.parquet

In [140]:
prices_in = pd.read_parquet(absolute_path / "prices_in_sample.parquet")
prices_out = pd.read_parquet(absolute_path / "prices_out_of_sample.parquet")
prices_w_in = pd.read_parquet(absolute_path / "prices_in_sample_w_contract_id.parquet")
prices_w_out = pd.read_parquet(absolute_path / "prices_out_of_sample_w_contract_id.parquet")
bid_ask_in = pd.read_parquet(absolute_path / "bidask_in_sample.parquet")
bid_ask_out = pd.read_parquet(absolute_path / "bidask_out_of_sample.parquet")


pd.testing.assert_frame_equal(prices_in, data.data_in)
pd.testing.assert_frame_equal(prices_out, data.data_out)
pd.testing.assert_frame_equal(prices_w_in, data.data_w_contract_id_in)
pd.testing.assert_frame_equal(prices_w_out, data.data_w_contract_id_out)
#pd.testing.assert_frame_equal(bid_ask_in, data.bid_ask_in)
#pd.testing.assert_frame_equal(bid_ask_out, data.bid_ask_out)

In [159]:
df_bidask_in[["EM_M_1_bid","EM_M_1_ask"]].loc["2025-03-05 10:00":]

                           EM_M_1_bid  EM_M_1_ask
index
2025-03-05 10:00:00+01:00   38.239998   38.349998
2025-03-05 10:01:00+01:00   38.610001   38.699997
2025-03-05 10:02:00+01:00   38.860001   38.970001
2025-03-05 10:03:00+01:00   39.000000   39.110001
2025-03-05 10:04:00+01:00   39.059998   39.199997
...                               ...         ...
2025-09-30 17:56:00+02:00   45.639999   45.739998
2025-09-30 17:57:00+02:00   45.620003   45.739998
2025-09-30 17:58:00+02:00   45.620003   45.739998
2025-09-30 17:59:00+02:00   45.639999   45.760002
2025-09-30 18:00:00+02:00   45.599998   46.500000

[81593 rows x 2 columns]

In [150]:
march = loader.load(month="march")

In [160]:
march[march.product_id == "EM_M_1"].loc["2025-03-05 10:00":]

,product_id,sf_contract_id,price,best_bid,best_ask,contract_id
ts,,,,,,
2025-03-05 10:00:00+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,38.305838,38.239998,38.349998,0
2025-03-05 10:00:01+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,38.317448,38.239998,38.370003,0
2025-03-05 10:00:02+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,38.300012,38.199997,38.370003,0
2025-03-05 10:00:03+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,38.318914,38.260002,38.370003,0
2025-03-05 10:00:04+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,38.325467,38.260002,38.370003,0
...,...,...,...,...,...,...
2025-03-26 17:59:55+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,40.672170,40.629997,40.720001,0
2025-03-26 17:59:58+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,40.703617,40.669998,40.739998,0
2025-03-26 17:59:59+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,40.706500,40.669998,40.739998,0
2025-03-26 18:00:00+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,40.682990,40.639999,40.730003,0
2025-03-26 18:00:01+01:00,EM_M_1,EM_EUA_EEX_M_OTHER_2025-12-01,NaN,39.970001,41.849998,0