In [98]:
import settings
import pandas as pd
import importlib
import strategy
import plots_statistics
importlib.reload(plots_statistics)
importlib.reload(strategy)
from plots_statistics import calculate_total_pnl
from strategy import run_multiple_contracts
from settings import load_project_data

In [99]:
data = load_project_data()
open_until = settings.open_until
close_until = settings.close_time_limit
contracts = settings.BEST_PREDICTORS.keys()
dict_thresholds = settings.BEST_PREDICTORS

In [100]:
#IN SAMPLE TRADES - MULTI ENTRY
prediction_path = "/Users/filipekrt/SF/Ekrt/sf_project/predictions_in_sample"
trades_in = run_multiple_contracts(data.data_in, data.bid_ask_in, contracts, dict_thresholds, open_until, close_until, prediction_path)
#trades_in.to_parquet(settings.ROOT / "sf_project" / "trades_in_sample.parquet")

Processing GAS_M_1...
Processing GAS_M_2...
Processing EM_M_1...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prediction = pd.read_parquet(pred_file)

Processing QY_2...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prediction = pd.read_parquet(pred_file)

Processing QY_3...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prediction = pd.read_parquet(pred_file)

Processing QY_4...
Processing QY_5...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prediction = pd.read_parquet(pred_file)

Processing Y_2...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prediction = pd.read_parquet(pred_file)

Processing M_2...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prediction = pd.read_parquet(pred_file)

Processing M_3...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prediction = pd.read_parquet(pred_file)

Processing M_4...
Processing M_5...
Processing IT_M_1...
Processing IT_QY_1...

In [101]:
trades_in

,threshold,contract,day,trade_type,t_open,t_close,entry_price,close_price,new_opened,total_opened_for_now,pnl
0,0.075,GAS_M_1,2025-03-05,Short,2025-03-05 08:47:00+01:00,2025-03-05 11:00:00+01:00,28.439999,28.651433,2,2,-0.422868
1,0.100,GAS_M_1,2025-03-07,Long,2025-03-07 08:44:00+01:00,2025-03-07 11:00:00+01:00,21.869999,25.002490,3,3,9.397473
2,0.050,GAS_M_1,2025-03-17,Long,2025-03-17 09:15:00+01:00,2025-03-17 11:00:00+01:00,26.840000,26.532768,1,1,-0.307233
3,0.050,GAS_M_1,2025-03-18,Short,2025-03-18 09:40:00+01:00,2025-03-18 11:00:00+01:00,25.715000,25.951797,1,1,-0.236797
4,0.075,GAS_M_1,2025-03-21,Short,2025-03-21 08:28:00+01:00,2025-03-21 11:00:00+01:00,29.580002,28.674869,2,2,1.810266
...,...,...,...,...,...,...,...,...,...,...,...
1366,0.350,IT_QY_1,2025-07-21,Long,2025-07-21 09:34:00+02:00,2025-07-21 11:00:00+02:00,83.580002,83.862340,1,1,0.282339
1367,0.350,IT_QY_1,2025-07-30,Long,2025-07-30 09:37:00+02:00,2025-07-30 11:00:00+02:00,86.000000,84.632683,1,1,-1.367317
1368,0.525,IT_QY_1,2025-08-22,Short,2025-08-22 08:47:00+02:00,2025-08-22 11:00:00+02:00,82.010002,81.775853,2,2,0.468299
1369,0.700,IT_QY_1,2025-08-22,Short,2025-08-22 09:03:00+02:00,2025-08-22 11:00:00+02:00,81.699997,81.775853,1,3,-0.075856
1370,0.350,IT_QY_1,2025-08-28,Short,2025-08-28 08:34:00+02:00,2025-08-28 11:00:00+02:00,79.500000,78.306362,1,1,1.193638

In [102]:
#OUT-OF-SAMPLE TRADES - MULTI ENTRY
prediction_path = "/Users/filipekrt/SF/Ekrt/sf_project/predictions_out_of_sample"
trades_out = run_multiple_contracts(data.data_out, data.bid_ask_out, contracts, dict_thresholds, open_until, close_until, prediction_path)
#trades_out.to_parquet(settings.ROOT / "sf_project" / "trades_out_of_sample.parquet")

Processing GAS_M_1...
Processing GAS_M_2...
Processing EM_M_1...
Processing QY_2...
Processing QY_3...
Processing QY_4...
Processing QY_5...
Processing Y_2...
Processing M_2...
Processing M_3...
Processing M_4...
Processing M_5...
Processing IT_M_1...
Processing IT_QY_1...

In [103]:
trades_out

,threshold,contract,day,trade_type,t_open,t_close,entry_price,close_price,new_opened,total_opened_for_now,pnl
0,0.050,GAS_M_1,2025-10-02,Short,2025-10-02 08:12:00+02:00,2025-10-02 11:00:00+02:00,16.639999,16.291491,1,1,0.348508
1,0.075,GAS_M_1,2025-10-06,Short,2025-10-06 09:30:00+02:00,2025-10-06 11:00:00+02:00,17.630001,17.575400,2,2,0.109201
2,0.050,GAS_M_1,2025-10-09,Long,2025-10-09 08:19:00+02:00,2025-10-09 11:00:00+02:00,17.110001,17.255712,1,1,0.145711
3,0.050,GAS_M_1,2025-10-10,Short,2025-10-10 08:07:00+02:00,2025-10-10 11:00:00+02:00,17.224998,16.947016,1,1,0.277982
4,0.050,GAS_M_1,2025-10-13,Short,2025-10-13 09:00:00+02:00,2025-10-13 11:00:00+02:00,16.795000,16.809440,1,1,-0.014440
...,...,...,...,...,...,...,...,...,...,...,...
541,0.350,IT_M_1,2025-12-18,Short,2025-12-18 08:53:00+01:00,2025-12-18 11:00:00+01:00,84.059998,84.350161,1,1,-0.290163
542,0.350,IT_QY_1,2025-11-21,Short,2025-11-21 09:01:00+01:00,2025-11-21 11:00:00+01:00,81.160004,81.053996,1,1,0.106007
543,0.525,IT_QY_1,2025-11-21,Short,2025-11-21 09:04:00+01:00,2025-11-21 11:00:00+01:00,81.400002,81.053996,1,2,0.346005
544,0.350,IT_QY_1,2025-12-15,Short,2025-12-15 09:26:00+01:00,2025-12-15 11:00:00+01:00,79.139999,79.041054,1,1,0.098945
545,0.350,IT_QY_1,2025-12-17,Long,2025-12-17 09:29:00+01:00,2025-12-17 11:00:00+01:00,78.860001,79.119999,1,1,0.259998

In [104]:
calculate_total_pnl(trades_out)

                    PnL
EM_M_1     11924.583238
GAS_M_1     1493.649492
GAS_M_2      -30.148574
M_1            0.000000
M_2        23317.305501
M_3        10483.040429
M_4         2322.218446
M_5          -46.929680
IT_M_1      5611.908512
QY_1           0.000000
QY_2       21577.571670
QY_3       -5248.682337
QY_4        3543.219681
QY_5       -2982.150289
QY_6           0.000000
IT_QY_1     1751.664104
Y_1            0.000000
Y_2        19728.945819
Total_PnL  93446.196011

In [105]:
calculate_total_pnl(trades_in)

                     PnL
EM_M_1      19527.022144
GAS_M_1     13474.607117
GAS_M_2      9985.044044
M_1             0.000000
M_2         18462.924786
M_3         -6040.999500
M_4          8746.403273
M_5          -713.466747
IT_M_1      19277.330769
QY_1            0.000000
QY_2        76316.775505
QY_3        52801.869008
QY_4        38346.503389
QY_5        30198.602144
QY_6            0.000000
IT_QY_1     49397.179145
Y_1             0.000000
Y_2        128394.064494
Total_PnL  458173.859573

In [88]:
#SINGLE- ENTRY - IN SAMPLE
#Zde jen pro jednoduchost nastav threshold 0.1 pro všechny
dict = {}
for target_col in contracts:
    dict[target_col] = 0.2
prediction_path = "/Users/filipekrt/SF/Ekrt/sf_project/predictions_in_sample"
single_trades_in = run_multiple_contracts(data.data_in, data.bid_ask_in, contracts, dict, open_until, close_until, prediction_path)

Processing GAS_M_1...
Processing GAS_M_2...
Processing EM_M_1...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:258: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Processing QY_2...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:258: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Processing QY_3...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:258: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Processing QY_4...
Processing QY_5...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:258: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Processing Y_2...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:258: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Processing M_2...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:258: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Processing M_3...

/Users/filipekrt/SF/Ekrt/sf_project/strategy.py:258: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Processing M_4...
Processing M_5...
Processing IT_M_1...
Processing IT_QY_1...